name: CI/CD 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run tests
      run: |
        pytes
      # your existing CI steps: checkout, install, run tests etc.

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: ${{ success() && github.ref == 'refs/heads/main' }}  # only if tests passed & main branch
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Push to staging branch
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git fetch origin
          git checkout -b staging
          git push -f origin staging
